spring:
  application:
    name: webchat_backend
    time_zone: GMT+7
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: GMT+7
      hibernate.enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
    main:
      allow-bean-definition-overriding: true
    mvc:
      favicon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: false

app:
  storage:
    folder-upload: uploads
    public-storage-url: http://localhost:8081/api/files
